services:

  mynginx:
    build:
      context: .
      args:
        - USER=101
        - GROUP=101
      dockerfile: Dockerfile
      tags:
        - "mynginx:1.27.3-alpine3.21.3"
    image: mynginx:latest
    ports:
      - 8080:8080/tcp
    volumes:
      - "./nginx/http.d:/etc/nginx/http.d"
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled"
