services:

  mydjangogirls_migration:
    build:
      context: .
      args:
        - IMAGE=python:3.11-alpine3.21
        - UID=101
        - GID=101
        - USERNAME=djangogirls
        - GROUPNAME=djangogirls
      dockerfile: ./Dockerfile
      tags: 
        - "mydjangogirls:python3.11-alpine3.21"
    pull_policy: build
    image: mydjangogirls:latest
    env_file: ./djangogirls.env
    volumes:
      - "~/docker_volumes/lab2/db:/app/db"

  mydjangogirls_start:
    image: mydjangogirls:latest
    env_file:
      - ./djangogirls.env
    ports:
      - 8000:8000/tcp
    volumes:
      - "~/docker_volumes/lab2/db:/app/db"
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      mydjangogirls_migration:
        condition: service_completed_successfully

